// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL5lNc4xJTVzQzd_PbeELM7DyuOwi_QyM',
    appId: '1:351694390736:web:8f478465bd0e5b62e625d5',
    messagingSenderId: '351694390736',
    projectId: 'inventory-app-75e2b',
    authDomain: 'inventory-app-75e2b.firebaseapp.com',
    storageBucket: 'inventory-app-75e2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChiaYlYMwc3aOad8_jXrQhXc-Ow1wnBPA',
    appId: '1:351694390736:android:f859d24ec989f79fe625d5',
    messagingSenderId: '351694390736',
    projectId: 'inventory-app-75e2b',
    storageBucket: 'inventory-app-75e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlvb8H05JURcQQ0eD1_-6jeksxiT5x7eE',
    appId: '1:351694390736:ios:6266a130151f7ed9e625d5',
    messagingSenderId: '351694390736',
    projectId: 'inventory-app-75e2b',
    storageBucket: 'inventory-app-75e2b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlvb8H05JURcQQ0eD1_-6jeksxiT5x7eE',
    appId: '1:351694390736:ios:6266a130151f7ed9e625d5',
    messagingSenderId: '351694390736',
    projectId: 'inventory-app-75e2b',
    storageBucket: 'inventory-app-75e2b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL5lNc4xJTVzQzd_PbeELM7DyuOwi_QyM',
    appId: '1:351694390736:web:061e9514a27a1cdbe625d5',
    messagingSenderId: '351694390736',
    projectId: 'inventory-app-75e2b',
    authDomain: 'inventory-app-75e2b.firebaseapp.com',
    storageBucket: 'inventory-app-75e2b.firebasestorage.app',
  );

}